/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    content: ContentBlock;
    featureSection: FeatureSection;
    pricingPlans: PricingPlansBlock;
    brandLogos: BrandLogosBlock;
    faqSection: FaqSectionBlock;
    dashboardSection: DashboardSectionBlockV2;
    integrationsSection: IntegrationsSection;
    testimonialsSection: TestimonialsSectionBlock;
    featuresWithIntroSection: FeaturesWithIntroSectionBlock;
    heroSection02: HeroSection02Payload;
    WhyChooseUsSection: WhyChooseUsSection;
    RecentArticles: RecentArticlesBlock;
    ContactForm: ContactFormBlock;
  };
  collections: {
    users: User;
    media: Media;
    hotels: Hotel;
    restaurants: Restaurant;
    experiences: Experience;
    categories: Category;
    'web-pages': WebPage;
    'wiki-pages': WikiPage;
    'registry-pages': RegistryPage;
    'navigation-cache': NavigationCache;
    'page-templates': PageTemplate;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    hotels: HotelsSelect<false> | HotelsSelect<true>;
    restaurants: RestaurantsSelect<false> | RestaurantsSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'web-pages': WebPagesSelect<false> | WebPagesSelect<true>;
    'wiki-pages': WikiPagesSelect<false> | WikiPagesSelect<true>;
    'registry-pages': RegistryPagesSelect<false> | RegistryPagesSelect<true>;
    'navigation-cache': NavigationCacheSelect<false> | NavigationCacheSelect<true>;
    'page-templates': PageTemplatesSelect<false> | PageTemplatesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    footer: Footer;
  };
  globalsSelect: {
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureSection".
 */
export interface FeatureSection {
  /**
   * Select the background color.
   */
  sectionBackgroundColor?: ('none' | 'white' | 'brand-50' | 'gradient') | null;
  /**
   * Select the background color.
   */
  contentBackgroundColor?: ('none' | 'white' | 'brand-50' | 'gradient') | null;
  /**
   * Select the maximum width for the content container within this block.
   */
  containerWidth?: ('default' | 'medium' | 'wide' | 'full') | null;
  superTitle?: string | null;
  title: string;
  /**
   * Select the display style for the title. "Large" matches the homepage hero title size.
   */
  titleStyle?: ('standard' | 'large') | null;
  description?: string | null;
  image?: (string | null) | Media;
  button?: {
    text: string;
    url: string;
    style: 'primary' | 'secondary';
  };
  includeButton?: boolean | null;
  /**
   * Check this to remove the default bottom padding from this section.
   */
  removeBottomPadding?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingPlansBlock".
 */
export interface PricingPlansBlock {
  eyebrowText?: string | null;
  title?: string | null;
  mainCtaText?: string | null;
  mainCtaLink?: string | null;
  mainCtaStyle?: ('primary' | 'secondary') | null;
  sectionBackgroundColor?: ('white' | 'light-grey' | 'brand-50' | 'brand-900' | 'brand-primary') | null;
  removeTopPadding?: boolean | null;
  removeBottomPadding?: boolean | null;
  plans?:
    | {
        name: string;
        description?: string | null;
        monthlyPrice?: string | null;
        annualPrice?: string | null;
        priceSuffix?: string | null;
        /**
         * Select a background color for this plan card. Ensure the Tailwind class exists.
         */
        cardBackgroundColor?: ('bg-white' | 'bg-light-grey' | 'bg-sand' | 'bg-brand-50') | null;
        ctaButtonLabel?: string | null;
        ctaButtonLink?: string | null;
        isMostPopular?: boolean | null;
        id?: string | null;
      }[]
    | null;
  sharedFeatures?:
    | {
        featureName: string;
        plan1Availability?: ('included' | 'not_included' | 'custom') | null;
        plan1CustomText?: string | null;
        plan2Availability?: ('included' | 'not_included' | 'custom') | null;
        plan2CustomText?: string | null;
        plan3Availability?: ('included' | 'not_included' | 'custom') | null;
        plan3CustomText?: string | null;
        /**
         * Short explanation for the feature, shown on hover or info icon.
         */
        tooltip?: string | null;
        id?: string | null;
      }[]
    | null;
  compareTableTitle?: string | null;
  compareTableDescription?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricingPlans';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandLogosBlock".
 */
export interface BrandLogosBlock {
  /**
   * Optional title to display above the logos.
   */
  title?: string | null;
  logos?:
    | {
        logoImage: string | Media;
        /**
         * Descriptive text for the logo image (for accessibility).
         */
        altText?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Select the background color for the logo section.
   */
  backgroundColor?: ('dark' | 'light' | 'transparent') | null;
  paddingTop?: ('none' | 'small' | 'medium' | 'large') | null;
  paddingBottom?: ('none' | 'small' | 'medium' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'brandLogos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqSectionBlock".
 */
export interface FaqSectionBlock {
  eyebrow?: string | null;
  /**
   * Select a background color for the eyebrow. Defaults to Theme Color 2.
   */
  eyebrowBackgroundColor?:
    | (
        | 'bg-brandTheme-01'
        | 'bg-brandTheme-02'
        | 'bg-brandTheme-03'
        | 'bg-brandTheme-04'
        | 'bg-brandNeutral-01'
        | 'bg-brandNeutral-04'
      )
    | null;
  /**
   * Optional image to display next to the title/subtitle (on larger screens).
   */
  titleImage?: (string | null) | Media;
  title: string;
  description?: string | null;
  faqs: {
    question: string;
    answer: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DashboardSectionBlockV2".
 */
export interface DashboardSectionBlockV2 {
  eyebrowText?: string | null;
  /**
   * Select a background color for the eyebrow. Defaults to Theme Color 2.
   */
  eyebrowBackgroundColor?:
    | (
        | 'bg-brandTheme-01'
        | 'bg-brandTheme-02'
        | 'bg-brandTheme-03'
        | 'bg-brandTheme-04'
        | 'bg-brandNeutral-01'
        | 'bg-brandNeutral-04'
      )
    | null;
  title: string;
  description: string;
  primaryButton: {
    text: string;
    url: string;
  };
  image: string | Media;
  stats?:
    | {
        icon?: (string | null) | Media;
        label: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dashboardSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrationsSection".
 */
export interface IntegrationsSection {
  eyebrow?: string | null;
  title: string;
  description?: string | null;
  titleImage?: (string | null) | Media;
  logos?:
    | {
        logoImage: string | Media;
        altText?: string | null;
        backgroundColorClass?:
          | (
              | 'theme-color-01'
              | 'theme-color-02'
              | 'theme-color-03'
              | 'theme-color-04'
              | 'purple'
              | 'green'
              | 'yellow'
              | 'purple-light'
              | 'default'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  button: {
    text: string;
    url: string;
    variant?: ('border' | 'primary' | 'secondary' | 'tertiary') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'integrationsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsSectionBlock".
 */
export interface TestimonialsSectionBlock {
  eyebrowText?: string | null;
  titleImage?: (string | null) | Media;
  title: string;
  description?: string | null;
  caseStudies?:
    | {
        quoteTitle?: string | null;
        quote: string;
        authorName: string;
        /**
         * Upload a square image for the author/person.
         */
        authorImage?: (string | null) | Media;
        authorRole?: string | null;
        /**
         * Upload a square company logo for the top of the card.
         */
        companyLogo?: (string | null) | Media;
        companyLogoBackgroundColor?:
          | (
              | 'theme-color-01'
              | 'theme-color-02'
              | 'theme-color-03'
              | 'theme-color-04'
              | 'purple'
              | 'green'
              | 'yellow'
              | 'purple-light'
              | 'default'
            )
          | null;
        /**
         * Enter the full URL for the case study.
         */
        readMoreLink?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesWithIntroSectionBlock".
 */
export interface FeaturesWithIntroSectionBlock {
  /**
   * Select the background color for the entire section.
   */
  sectionBackgroundColor?: ('none' | 'white' | 'brand-50' | 'gradient') | null;
  /**
   * Select the background color for the content area within the section padding.
   */
  contentBackgroundColor?: ('none' | 'white' | 'brand-50') | null;
  removeTopPadding?: boolean | null;
  removeBottomPadding?: boolean | null;
  introContent: {
    superTitle?: string | null;
    eyebrowBackgroundColor?:
      | (
          | 'bg-brandTheme-01'
          | 'bg-brandTheme-02'
          | 'bg-brandTheme-03'
          | 'bg-brandTheme-04'
          | 'bg-brandNeutral-01'
          | 'bg-brandNeutral-04'
        )
      | null;
    title: string;
    description?: string | null;
    /**
     * Optional image for the introductory header section.
     */
    titleImage?: (string | null) | Media;
  };
  featureItems?:
    | {
        title?: string | null;
        /**
         * Select the display style for the title. "Large" matches the homepage hero title size.
         */
        titleStyle?: ('standard' | 'large') | null;
        description?: string | null;
        image?: (string | null) | Media;
        imagePosition: 'left' | 'right';
        /**
         * Select a background color for the image container. Defaults to None (Transparent).
         */
        imageBackgroundColor?:
          | (
              | 'none'
              | 'brandTheme-01'
              | 'brandTheme-02'
              | 'brandTheme-03'
              | 'brandTheme-04'
              | 'brandNeutral-01'
              | 'brandNeutral-02'
              | 'brandNeutral-03'
              | 'brandNeutral-04'
              | 'white'
            )
          | null;
        buttons?:
          | {
              text: string;
              url: string;
              style: 'primary' | 'secondary';
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuresWithIntroSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSection02Payload".
 */
export interface HeroSection02Payload {
  /**
   * Optional small text displayed above the main heading.
   */
  eyebrowText?: string | null;
  heading?: string | null;
  subheading?: string | null;
  buttons?:
    | {
        label: string;
        variant: 'primary' | 'secondary' | 'tertiary' | 'border';
        type?: ('internal' | 'external') | null;
        internalLink?: (string | null) | WebPage;
        externalLink?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The main image for the hero section.
   */
  heroImage?: (string | null) | Media;
  arrowButtonText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroSection02';
}
/**
 * General website pages (e.g., Homepage).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-pages".
 */
export interface WebPage {
  id: string;
  title: string;
  /**
   * A unique identifier for the page, used in the URL.
   */
  slug: string;
  /**
   * Optimize your page for search engines and social sharing.
   */
  meta?: {
    /**
     * Custom title for search engines. If blank, the page title will be used.
     */
    title?: string | null;
    /**
     * Brief description of this page for search results and social sharing.
     */
    description?: string | null;
    /**
     * Image used when sharing this page on social media (1200×630px recommended).
     */
    image?: (string | null) | Media;
    /**
     * If checked, this page will not be indexed by search engines.
     */
    noIndex?: boolean | null;
    /**
     * The type of content this page represents (for structured data).
     */
    schemaType?: ('Article' | 'WebPage' | 'FAQPage' | 'Product' | 'Service' | 'Organization') | null;
    /**
     * Comma-separated keywords (optional).
     */
    keywords?: string | null;
    /**
     * Automatically generated Schema.org JSON-LD markup. Can be overridden if needed.
     */
    jsonLD?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  layout: (
    | ContentBlock
    | FeatureSection
    | PricingCardsBlock
    | FeatureComparisonTableBlock
    | BrandLogosBlock
    | FaqSectionBlock
    | DashboardSectionBlockV2
    | {
        eyebrow?: string | null;
        title: string;
        description?: string | null;
        titleImage?: (string | null) | Media;
        logos?:
          | {
              logoImage: string | Media;
              altText?: string | null;
              backgroundColorClass?:
                | (
                    | 'theme-color-01'
                    | 'theme-color-02'
                    | 'theme-color-03'
                    | 'theme-color-04'
                    | 'purple'
                    | 'green'
                    | 'yellow'
                    | 'purple-light'
                    | 'default'
                  )
                | null;
              id?: string | null;
            }[]
          | null;
        button: {
          text: string;
          url: string;
          variant?: ('border' | 'primary' | 'secondary' | 'tertiary') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'integrationsSection';
      }
    | TestimonialsSectionBlock
    | FeaturesWithIntroSectionBlock
    | HeroSection02Payload
    | {
        /**
         * Small text appearing above the main title, often styled as a tag.
         */
        eyebrowText?: string | null;
        /**
         * Select a background color for the eyebrow text pill.
         */
        eyebrowBackgroundColor?:
          | (
              | 'bg-brandTheme-01'
              | 'bg-brandTheme-02'
              | 'bg-brandTheme-03'
              | 'bg-brandTheme-04'
              | 'bg-brandNeutral-01'
              | 'bg-brandNeutral-02'
            )
          | null;
        title: string;
        subTitle?: string | null;
        /**
         * This image will appear to the right of the title and subtitle on medium screens and up. It will be hidden on mobile.
         */
        titleImage?: (string | null) | Media;
        cards?:
          | {
              icon: string | Media;
              /**
               * Select a theme color for the icon background.
               */
              iconBackgroundColor?:
                | ('bg-brandTheme-01' | 'bg-brandTheme-02' | 'bg-brandTheme-03' | 'bg-brandTheme-04')
                | null;
              cardTitle: string;
              cardText: string;
              /**
               * If checked, the card will have a colored background (using the Icon Background Color) and the icon will have a white background.
               */
              invertStyle?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'WhyChooseUsSection';
      }
    | RecentArticlesBlock
    | ContactFormBlock
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingCardsBlock".
 */
export interface PricingCardsBlock {
  eyebrowText?: string | null;
  title?: string | null;
  description?: string | null;
  headerImage?: (string | null) | Media;
  enableBillingToggle?: boolean | null;
  sectionBackgroundColor?: ('white' | 'light-grey' | 'brand-50' | 'brand-900' | 'brand-primary') | null;
  removeTopPadding?: boolean | null;
  removeBottomPadding?: boolean | null;
  plans?:
    | {
        name: string;
        description?: string | null;
        monthlyPrice?: string | null;
        annualPrice?: string | null;
        priceSuffix?: string | null;
        /**
         * Select a background color for this plan card. Popular plans will use Brand Primary by default. "None" also uses the default creamy off-white.
         */
        cardBackgroundColor?:
          | (
              | 'default'
              | 'none'
              | 'bg-brandTheme-01'
              | 'bg-brandTheme-02'
              | 'bg-brandTheme-03'
              | 'bg-brandTheme-04'
              | 'bg-pink-light'
              | 'bg-purple-light'
              | 'bg-brand-primary'
            )
          | null;
        ctaButtonLabel?: string | null;
        ctaButtonLink?: string | null;
        isMostPopular?: boolean | null;
        planSpecificFeatures?:
          | {
              featureText: string;
              isIncluded?: boolean | null;
              tooltip?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  sectionCtaText?: string | null;
  sectionCtaLink?: string | null;
  sectionCtaStyle?: ('primary' | 'secondary') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricingCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureComparisonTableBlock".
 */
export interface FeatureComparisonTableBlock {
  eyebrowText?: string | null;
  title?: string | null;
  description?: string | null;
  headerImage?: (string | null) | Media;
  sectionBackgroundColor?: ('white' | 'light-grey' | 'brand-50' | 'brand-900' | 'brand-primary') | null;
  removeTopPadding?: boolean | null;
  removeBottomPadding?: boolean | null;
  planHeaders?:
    | {
        name: string;
        isMostPopular?: boolean | null;
        id?: string | null;
      }[]
    | null;
  sharedFeatures?:
    | {
        featureName: string;
        /**
         * Corresponds to the first plan defined in Plan Headers.
         */
        plan1Availability?: ('included' | 'not_included' | 'custom') | null;
        plan1CustomText?: string | null;
        /**
         * Corresponds to the second plan defined in Plan Headers (if it exists).
         */
        plan2Availability?: ('included' | 'not_included' | 'custom') | null;
        plan2CustomText?: string | null;
        /**
         * Corresponds to the third plan defined in Plan Headers (if it exists).
         */
        plan3Availability?: ('included' | 'not_included' | 'custom') | null;
        plan3CustomText?: string | null;
        /**
         * Short explanation for the feature, shown on hover or info icon.
         */
        tooltip?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureComparisonTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RecentArticlesBlock".
 */
export interface RecentArticlesBlock {
  eyebrowText?: string | null;
  eyebrowBackgroundColor?:
    | (
        | 'theme-color-01'
        | 'theme-color-02'
        | 'theme-color-03'
        | 'theme-color-04'
        | 'purple'
        | 'green'
        | 'yellow'
        | 'purple-light'
        | 'default'
      )
    | null;
  title: string;
  subTitle?: string | null;
  articles?:
    | {
        image: string | Media;
        /**
         * Small text displayed above the article title, styled as a pill (e.g., date or category).
         */
        eyebrowText?: string | null;
        articleEyebrowBackgroundColor?:
          | (
              | 'theme-color-01'
              | 'theme-color-02'
              | 'theme-color-03'
              | 'theme-color-04'
              | 'purple'
              | 'green'
              | 'yellow'
              | 'purple-light'
              | 'default'
            )
          | null;
        articleTitle: string;
        articleExcerpt: string;
        buttonText: string;
        link: {
          type?: ('internal' | 'external') | null;
          label: string;
          internalLink?: (string | null) | WebPage;
          externalLink?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'RecentArticles';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock".
 */
export interface ContactFormBlock {
  contentEyebrow?: string | null;
  contentTitle?: string | null;
  contentDescription?: string | null;
  contentImage?: (string | null) | Media;
  contentImagePosition?: ('above' | 'below') | null;
  /**
   * Optional title displayed directly above the form fields.
   */
  formTitle?: string | null;
  /**
   * Email address where form submissions will be sent.
   */
  recipientEmail: string;
  submitButtonText?: string | null;
  showNameField?: boolean | null;
  requireNameField?: boolean | null;
  showCompanyField?: boolean | null;
  requireCompanyField?: boolean | null;
  showSubjectField?: boolean | null;
  requireSubjectField?: boolean | null;
  showMessageField?: boolean | null;
  requireMessageField?: boolean | null;
  messageFieldLabel?: string | null;
  /**
   * Text that appears before the privacy policy link. The link itself is configured below.
   */
  privacyPolicyText?: string | null;
  link: {
    type?: ('internal' | 'external') | null;
    label: string;
    internalLink?: (string | null) | WebPage;
    externalLink?: string | null;
    newTab?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ContactForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyChooseUsSection".
 */
export interface WhyChooseUsSection {
  /**
   * Small text appearing above the main title, often styled as a tag.
   */
  eyebrowText?: string | null;
  /**
   * Select a background color for the eyebrow text pill.
   */
  eyebrowBackgroundColor?:
    | (
        | 'bg-brandTheme-01'
        | 'bg-brandTheme-02'
        | 'bg-brandTheme-03'
        | 'bg-brandTheme-04'
        | 'bg-brandNeutral-01'
        | 'bg-brandNeutral-02'
      )
    | null;
  title: string;
  subTitle?: string | null;
  /**
   * This image will appear to the right of the title and subtitle on medium screens and up. It will be hidden on mobile.
   */
  titleImage?: (string | null) | Media;
  cards?:
    | {
        icon: string | Media;
        /**
         * Select a theme color for the icon background.
         */
        iconBackgroundColor?:
          | ('bg-brandTheme-01' | 'bg-brandTheme-02' | 'bg-brandTheme-03' | 'bg-brandTheme-04')
          | null;
        cardTitle: string;
        cardText: string;
        /**
         * If checked, the card will have a colored background (using the Icon Background Color) and the icon will have a white background.
         */
        invertStyle?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'WhyChooseUsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hotels".
 */
export interface Hotel {
  id: string;
  name?: string | null;
  registryId?: string | null;
  mainDetails?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  description?: string | null;
  media?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  facts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  vibe?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  facilities?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  references?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reviews?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  walkScore?: number | null;
  poi?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rooms?:
    | {
        roomId: number;
        name: string;
        basics?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        description?: string | null;
        uniqueFeatures?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        idealFor?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        notBestFor?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        searchQueries?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        grade?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        amenities?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restaurants".
 */
export interface Restaurant {
  id: string;
  name: string;
  restaurantId: string;
  lastUpdated: string;
  identity?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  hierarchy?: {
    details?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  pricingContext?: {
    details?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  wouldMatch?: {
    details?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  media?: {
    details?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  culinaryDetails?: {
    details?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  operationalDetails?: {
    details?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  capacity?: {
    details?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  features?: {
    details?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  awards?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reviewSnippets?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  location?: {
    details?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  businessInfo?: {
    details?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  reviews?: {
    details?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  contextualInfo?: {
    details?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: string;
  name: string;
  experienceId: string;
  lastUpdated: string;
  identity: {
    name: string;
    experienceType: string;
    category?: string | null;
    subCategories?:
      | {
          subCategory?: string | null;
          id?: string | null;
        }[]
      | null;
    duration?: {
      typical?: string | null;
      minimum?: string | null;
      maximum?: string | null;
    };
    difficultyLevel?: string | null;
    descriptionShort: string;
  };
  hierarchy?: {
    tier?: string | null;
    upgradeFrom?: string | null;
    upgradeTo?: string | null;
    competitiveSet?:
      | {
          set?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  pricingContext?: {
    pricing?: {
      adult?: string | null;
      senior?: string | null;
      student?: string | null;
      child?: string | null;
      family?: string | null;
    };
    priceVsStandardAdmission?: string | null;
    valuePerception?: string | null;
  };
  wouldMatch?: {
    idealFor?:
      | {
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    notIdealFor?:
      | {
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    bestQueryTypes?:
      | {
          query?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  media?: {
    primaryImageUrl?: string | null;
    gallery?:
      | {
          url?: string | null;
          caption?: string | null;
          id?: string | null;
        }[]
      | null;
    videoUrl?: string | null;
    photoCount?: number | null;
  };
  experienceDetails?: {
    highlights?:
      | {
          highlight?: string | null;
          id?: string | null;
        }[]
      | null;
    inclusions?:
      | {
          inclusion?: string | null;
          id?: string | null;
        }[]
      | null;
    exclusions?:
      | {
          exclusion?: string | null;
          id?: string | null;
        }[]
      | null;
    meetingPoint?: string | null;
    endPoint?: string | null;
  };
  operationalDetails?: {
    schedule?: {
      availability?: string | null;
      tourTimes?:
        | {
            time?: string | null;
            id?: string | null;
          }[]
        | null;
      seasonalVariations?: {
        summer?: string | null;
        winter?: string | null;
      };
    };
    bookingRequirements?: {
      advanceBookingRequired?: boolean | null;
      bookingHorizon?: string | null;
      cancellationPolicy?: string | null;
      groupBookings?: string | null;
      walkInsAvailable?: string | null;
    };
    capacity?: {
      maximumGroupSize?: number | null;
      minimumGroupSize?: number | null;
      privateBookingMinimum?: number | null;
    };
  };
  requirements?: {
    ageRestrictions?: {
      minimumAge?: string | null;
      adultSupervision?: string | null;
    };
    physicalRequirements?:
      | {
          requirement?: string | null;
          id?: string | null;
        }[]
      | null;
    accessibility?: {
      wheelchairAccessible?: string | null;
      hearingLoop?: string | null;
      accessibilityNotes?: string | null;
    };
    whatToBring?:
      | {
          item?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  features?: {
    uniqueFeatures?:
      | {
          feature?: string | null;
          id?: string | null;
        }[]
      | null;
    educationalValue?: {
      learningOutcomes?:
        | {
            outcome?: string | null;
            id?: string | null;
          }[]
        | null;
      suitableFor?:
        | {
            group?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  guides?: {
    guideProfile?: {
      background?: string | null;
      experience?: string | null;
      languages?:
        | {
            language?: string | null;
            id?: string | null;
          }[]
        | null;
      specializations?:
        | {
            specialization?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    guideRatings?: {
      knowledgeScore?: number | null;
      engagementScore?: number | null;
      clarityScore?: number | null;
    };
  };
  seasonalConsiderations?: {
    bestTime?: string | null;
    weatherImpact?: string | null;
    specialEvents?:
      | {
          event?: string | null;
          id?: string | null;
        }[]
      | null;
    crowdingPatterns?: string | null;
  };
  reviewSnippets?:
    | {
        text: string;
        source: string;
        date: string;
        rating?: number | null;
        visitorType?: string | null;
        id?: string | null;
      }[]
    | null;
  location: {
    address: string;
    neighborhood?: string | null;
    walkabilityScore?: number | null;
    parkingOptions?:
      | {
          type?: string | null;
          cost?: string | null;
          capacity?: string | null;
          walkTime?: string | null;
          name?: string | null;
          id?: string | null;
        }[]
      | null;
    publicTransport?: {
      nearestBusStop?: string | null;
      trainStation?: string | null;
      busRoutes?:
        | {
            route?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    nearbyAttractions?:
      | {
          name?: string | null;
          walkTime?: string | null;
          type?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  businessInfo?: {
    operator?: string | null;
    contact?: {
      phone?: string | null;
      email?: string | null;
      website?: string | null;
      bookingPortal?: string | null;
    };
    operatedBy?: string | null;
    charitableStatus?: string | null;
  };
  reviews?: {
    aggregate?: {
      score?: number | null;
      count?: number | null;
      source?: string | null;
    };
    breakdown?: {
      content?: number | null;
      guide?: number | null;
      value?: number | null;
      organization?: number | null;
      uniqueness?: number | null;
    };
  };
  relatedExperiences?:
    | {
        experienceId?: string | null;
        name?: string | null;
        relationship?: string | null;
        combinedBooking?: string | null;
        duration?: string | null;
        id?: string | null;
      }[]
    | null;
  contextualInfo?: {
    localContext?: {
      culturalSignificance?: string | null;
      historicalImportance?: string | null;
      touristContext?: string | null;
    };
    bookingTips?:
      | {
          tip?: string | null;
          id?: string | null;
        }[]
      | null;
    combinationSuggestions?:
      | {
          suggestion?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Organize pages into hierarchical categories.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  /**
   * A unique identifier for the page, used in the URL.
   */
  slug: string;
  parent?: (string | null) | Category;
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pages for the wiki section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wiki-pages".
 */
export interface WikiPage {
  id: string;
  title: string;
  /**
   * A unique identifier for the page, used in the URL.
   */
  slug: string;
  category?: (string | null) | Category;
  pageBuilder: ContentBlock[];
  status: 'draft' | 'published';
  /**
   * Order in navigation (lower numbers appear first).
   */
  sort?: number | null;
  /**
   * If true, this page acts as the main page for its category/section.
   */
  isSectionHomepage?: boolean | null;
  parent?: (string | null) | WikiPage;
  /**
   * Optional icon name for navigation display.
   */
  icon?: string | null;
  /**
   * Background color for the icon circle. Select "None" for no background.
   */
  iconBackgroundColor?:
    | (
        | 'none'
        | 'bg-brandTheme-01'
        | 'bg-brandTheme-02'
        | 'bg-brandTheme-03'
        | 'bg-brandTheme-04'
        | 'bg-pink-light'
        | 'bg-purple-light'
      )
    | null;
  backgroundSettings?: {
    /**
     * Optional background image for the page.
     */
    backgroundImage?: (string | null) | Media;
    /**
     * Select a background color for the header area.
     */
    backgroundOverlay?:
      | (
          | 'default-gradient'
          | 'brandTheme-01'
          | 'brandTheme-02'
          | 'brandTheme-03'
          | 'brandTheme-04'
          | 'brandNeutral-01'
          | 'brandNeutral-02'
          | 'brandNeutral-03'
          | 'brandNeutral-04'
          | 'light-grey'
        )
      | null;
  };
  /**
   * Optimize your page for search engines and social sharing.
   */
  meta?: {
    /**
     * Custom title for search engines. If blank, the page title will be used.
     */
    title?: string | null;
    /**
     * Brief description of this page for search results and social sharing.
     */
    description?: string | null;
    /**
     * Image used when sharing this page on social media (1200×630px recommended).
     */
    image?: (string | null) | Media;
    /**
     * If checked, this page will not be indexed by search engines.
     */
    noIndex?: boolean | null;
    /**
     * The type of content this page represents (for structured data).
     */
    schemaType?: ('Article' | 'WebPage' | 'FAQPage' | 'Product' | 'Service' | 'Organization') | null;
    /**
     * Comma-separated keywords (optional).
     */
    keywords?: string | null;
    /**
     * Automatically generated Schema.org JSON-LD markup. Can be overridden if needed.
     */
    jsonLD?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Pages for the registry section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registry-pages".
 */
export interface RegistryPage {
  id: string;
  title: string;
  /**
   * A unique identifier for the page, used in the URL.
   */
  slug: string;
  category?: (string | null) | Category;
  /**
   * Select a template to use for this page.
   */
  template?: (string | null) | PageTemplate;
  pageBuilder: (
    | ContentBlock
    | {
        content: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'regRichText';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        backgroundColor?:
          | (
              | 'bg-brandTheme-01'
              | 'bg-brandTheme-02'
              | 'bg-brandTheme-03'
              | 'bg-brandTheme-04'
              | 'bg-pink-light'
              | 'bg-purple-light'
              | 'none'
            )
          | null;
        /**
         * Enter the Phosphor icon name, e.g., ph:info, ph:warning, ph:lightbulb
         */
        icon?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'regCallout';
      }
    | {
        images?:
          | {
              image: string | Media;
              id?: string | null;
            }[]
          | null;
        /**
         * Set how many thumbnails are visible in the carousel.
         */
        visibleThumbnails?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'regImageCarousel';
      }
    | {
        columns?:
          | {
              blocks?:
                | (
                    | {
                        content: {
                          root: {
                            type: string;
                            children: {
                              type: string;
                              version: number;
                              [k: string]: unknown;
                            }[];
                            direction: ('ltr' | 'rtl') | null;
                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                            indent: number;
                            version: number;
                          };
                          [k: string]: unknown;
                        };
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'regRichText';
                      }
                    | {
                        content: {
                          root: {
                            type: string;
                            children: {
                              type: string;
                              version: number;
                              [k: string]: unknown;
                            }[];
                            direction: ('ltr' | 'rtl') | null;
                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                            indent: number;
                            version: number;
                          };
                          [k: string]: unknown;
                        };
                        backgroundColor?:
                          | (
                              | 'bg-brandTheme-01'
                              | 'bg-brandTheme-02'
                              | 'bg-brandTheme-03'
                              | 'bg-brandTheme-04'
                              | 'bg-pink-light'
                              | 'bg-purple-light'
                              | 'none'
                            )
                          | null;
                        /**
                         * Enter the Phosphor icon name, e.g., ph:info, ph:warning, ph:lightbulb
                         */
                        icon?: string | null;
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'regCallout';
                      }
                    | {
                        title?: string | null;
                        /**
                         * Paste JSON or technical content here.
                         */
                        code: string;
                        showBorder?: boolean | null;
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'regCode';
                      }
                    | {
                        images?:
                          | {
                              image: string | Media;
                              id?: string | null;
                            }[]
                          | null;
                        /**
                         * Set how many thumbnails are visible in the carousel.
                         */
                        visibleThumbnails?: number | null;
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'regImageCarousel';
                      }
                  )[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'regColumns';
      }
    | {
        items?:
          | {
              title: string;
              content: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'regAccordion';
      }
    | {
        rows?:
          | {
              cells?:
                | {
                    value: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'regTable';
      }
    | {
        title?: string | null;
        /**
         * Paste JSON or technical content here.
         */
        code: string;
        showBorder?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'regCode';
      }
  )[];
  status: 'draft' | 'published';
  /**
   * Order in navigation (lower numbers appear first).
   */
  sort?: number | null;
  /**
   * If true, this page acts as the main page for its category/section.
   */
  isSectionHomepage?: boolean | null;
  parent?: (string | null) | RegistryPage;
  /**
   * Optional icon name for navigation display.
   */
  icon?: string | null;
  /**
   * Background color for the icon circle. Select "None" for no background.
   */
  iconBackgroundColor?:
    | (
        | 'none'
        | 'bg-brandTheme-01'
        | 'bg-brandTheme-02'
        | 'bg-brandTheme-03'
        | 'bg-brandTheme-04'
        | 'bg-pink-light'
        | 'bg-purple-light'
      )
    | null;
  backgroundSettings?: {
    /**
     * Optional background image for the page.
     */
    backgroundImage?: (string | null) | Media;
    /**
     * Select a background color for the header area.
     */
    backgroundOverlay?:
      | (
          | 'default-gradient'
          | 'brandTheme-01'
          | 'brandTheme-02'
          | 'brandTheme-03'
          | 'brandTheme-04'
          | 'brandNeutral-01'
          | 'brandNeutral-02'
          | 'brandNeutral-03'
          | 'brandNeutral-04'
          | 'light-grey'
        )
      | null;
  };
  /**
   * Optimize your page for search engines and social sharing.
   */
  meta?: {
    /**
     * Custom title for search engines. If blank, the page title will be used.
     */
    title?: string | null;
    /**
     * Brief description of this page for search results and social sharing.
     */
    description?: string | null;
    /**
     * Image used when sharing this page on social media (1200×630px recommended).
     */
    image?: (string | null) | Media;
    /**
     * If checked, this page will not be indexed by search engines.
     */
    noIndex?: boolean | null;
    /**
     * The type of content this page represents (for structured data).
     */
    schemaType?: ('Article' | 'WebPage' | 'FAQPage' | 'Product' | 'Service' | 'Organization') | null;
    /**
     * Comma-separated keywords (optional).
     */
    keywords?: string | null;
    /**
     * Automatically generated Schema.org JSON-LD markup. Can be overridden if needed.
     */
    jsonLD?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-templates".
 */
export interface PageTemplate {
  id: string;
  name: string;
  blocks?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'regRichText';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            backgroundColor?:
              | (
                  | 'bg-brandTheme-01'
                  | 'bg-brandTheme-02'
                  | 'bg-brandTheme-03'
                  | 'bg-brandTheme-04'
                  | 'bg-pink-light'
                  | 'bg-purple-light'
                  | 'none'
                )
              | null;
            /**
             * Enter the Phosphor icon name, e.g., ph:info, ph:warning, ph:lightbulb
             */
            icon?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'regCallout';
          }
        | {
            images?:
              | {
                  image: string | Media;
                  id?: string | null;
                }[]
              | null;
            /**
             * Set how many thumbnails are visible in the carousel.
             */
            visibleThumbnails?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'regImageCarousel';
          }
        | {
            columns?:
              | {
                  blocks?:
                    | (
                        | {
                            content: {
                              root: {
                                type: string;
                                children: {
                                  type: string;
                                  version: number;
                                  [k: string]: unknown;
                                }[];
                                direction: ('ltr' | 'rtl') | null;
                                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                indent: number;
                                version: number;
                              };
                              [k: string]: unknown;
                            };
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'regRichText';
                          }
                        | {
                            content: {
                              root: {
                                type: string;
                                children: {
                                  type: string;
                                  version: number;
                                  [k: string]: unknown;
                                }[];
                                direction: ('ltr' | 'rtl') | null;
                                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                indent: number;
                                version: number;
                              };
                              [k: string]: unknown;
                            };
                            backgroundColor?:
                              | (
                                  | 'bg-brandTheme-01'
                                  | 'bg-brandTheme-02'
                                  | 'bg-brandTheme-03'
                                  | 'bg-brandTheme-04'
                                  | 'bg-pink-light'
                                  | 'bg-purple-light'
                                  | 'none'
                                )
                              | null;
                            /**
                             * Enter the Phosphor icon name, e.g., ph:info, ph:warning, ph:lightbulb
                             */
                            icon?: string | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'regCallout';
                          }
                        | {
                            title?: string | null;
                            /**
                             * Paste JSON or technical content here.
                             */
                            code: string;
                            showBorder?: boolean | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'regCode';
                          }
                        | {
                            images?:
                              | {
                                  image: string | Media;
                                  id?: string | null;
                                }[]
                              | null;
                            /**
                             * Set how many thumbnails are visible in the carousel.
                             */
                            visibleThumbnails?: number | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'regImageCarousel';
                          }
                      )[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'regColumns';
          }
        | {
            items?:
              | {
                  title: string;
                  content: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'regAccordion';
          }
        | {
            rows?:
              | {
                  cells?:
                    | {
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'regTable';
          }
        | {
            title?: string | null;
            /**
             * Paste JSON or technical content here.
             */
            code: string;
            showBorder?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'regCode';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Navigation data cache for different sections of the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-cache".
 */
export interface NavigationCache {
  id: string;
  section: 'wiki' | 'registry';
  /**
   * JSON structure of the navigation (automatically generated)
   */
  navigationData:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lastGenerated?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'hotels';
        value: string | Hotel;
      } | null)
    | ({
        relationTo: 'restaurants';
        value: string | Restaurant;
      } | null)
    | ({
        relationTo: 'experiences';
        value: string | Experience;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'web-pages';
        value: string | WebPage;
      } | null)
    | ({
        relationTo: 'wiki-pages';
        value: string | WikiPage;
      } | null)
    | ({
        relationTo: 'registry-pages';
        value: string | RegistryPage;
      } | null)
    | ({
        relationTo: 'navigation-cache';
        value: string | NavigationCache;
      } | null)
    | ({
        relationTo: 'page-templates';
        value: string | PageTemplate;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hotels_select".
 */
export interface HotelsSelect<T extends boolean = true> {
  name?: T;
  registryId?: T;
  mainDetails?: T;
  description?: T;
  media?: T;
  facts?: T;
  vibe?: T;
  facilities?: T;
  references?: T;
  reviews?: T;
  walkScore?: T;
  poi?: T;
  rooms?:
    | T
    | {
        roomId?: T;
        name?: T;
        basics?: T;
        description?: T;
        uniqueFeatures?: T;
        idealFor?: T;
        notBestFor?: T;
        searchQueries?: T;
        grade?: T;
        amenities?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restaurants_select".
 */
export interface RestaurantsSelect<T extends boolean = true> {
  name?: T;
  restaurantId?: T;
  lastUpdated?: T;
  identity?: T;
  hierarchy?:
    | T
    | {
        details?: T;
      };
  pricingContext?:
    | T
    | {
        details?: T;
      };
  wouldMatch?:
    | T
    | {
        details?: T;
      };
  media?:
    | T
    | {
        details?: T;
      };
  culinaryDetails?:
    | T
    | {
        details?: T;
      };
  operationalDetails?:
    | T
    | {
        details?: T;
      };
  capacity?:
    | T
    | {
        details?: T;
      };
  features?:
    | T
    | {
        details?: T;
      };
  awards?: T;
  reviewSnippets?: T;
  location?:
    | T
    | {
        details?: T;
      };
  businessInfo?:
    | T
    | {
        details?: T;
      };
  reviews?:
    | T
    | {
        details?: T;
      };
  contextualInfo?:
    | T
    | {
        details?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  name?: T;
  experienceId?: T;
  lastUpdated?: T;
  identity?:
    | T
    | {
        name?: T;
        experienceType?: T;
        category?: T;
        subCategories?:
          | T
          | {
              subCategory?: T;
              id?: T;
            };
        duration?:
          | T
          | {
              typical?: T;
              minimum?: T;
              maximum?: T;
            };
        difficultyLevel?: T;
        descriptionShort?: T;
      };
  hierarchy?:
    | T
    | {
        tier?: T;
        upgradeFrom?: T;
        upgradeTo?: T;
        competitiveSet?:
          | T
          | {
              set?: T;
              id?: T;
            };
      };
  pricingContext?:
    | T
    | {
        pricing?:
          | T
          | {
              adult?: T;
              senior?: T;
              student?: T;
              child?: T;
              family?: T;
            };
        priceVsStandardAdmission?: T;
        valuePerception?: T;
      };
  wouldMatch?:
    | T
    | {
        idealFor?:
          | T
          | {
              description?: T;
              id?: T;
            };
        notIdealFor?:
          | T
          | {
              description?: T;
              id?: T;
            };
        bestQueryTypes?:
          | T
          | {
              query?: T;
              id?: T;
            };
      };
  media?:
    | T
    | {
        primaryImageUrl?: T;
        gallery?:
          | T
          | {
              url?: T;
              caption?: T;
              id?: T;
            };
        videoUrl?: T;
        photoCount?: T;
      };
  experienceDetails?:
    | T
    | {
        highlights?:
          | T
          | {
              highlight?: T;
              id?: T;
            };
        inclusions?:
          | T
          | {
              inclusion?: T;
              id?: T;
            };
        exclusions?:
          | T
          | {
              exclusion?: T;
              id?: T;
            };
        meetingPoint?: T;
        endPoint?: T;
      };
  operationalDetails?:
    | T
    | {
        schedule?:
          | T
          | {
              availability?: T;
              tourTimes?:
                | T
                | {
                    time?: T;
                    id?: T;
                  };
              seasonalVariations?:
                | T
                | {
                    summer?: T;
                    winter?: T;
                  };
            };
        bookingRequirements?:
          | T
          | {
              advanceBookingRequired?: T;
              bookingHorizon?: T;
              cancellationPolicy?: T;
              groupBookings?: T;
              walkInsAvailable?: T;
            };
        capacity?:
          | T
          | {
              maximumGroupSize?: T;
              minimumGroupSize?: T;
              privateBookingMinimum?: T;
            };
      };
  requirements?:
    | T
    | {
        ageRestrictions?:
          | T
          | {
              minimumAge?: T;
              adultSupervision?: T;
            };
        physicalRequirements?:
          | T
          | {
              requirement?: T;
              id?: T;
            };
        accessibility?:
          | T
          | {
              wheelchairAccessible?: T;
              hearingLoop?: T;
              accessibilityNotes?: T;
            };
        whatToBring?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  features?:
    | T
    | {
        uniqueFeatures?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        educationalValue?:
          | T
          | {
              learningOutcomes?:
                | T
                | {
                    outcome?: T;
                    id?: T;
                  };
              suitableFor?:
                | T
                | {
                    group?: T;
                    id?: T;
                  };
            };
      };
  guides?:
    | T
    | {
        guideProfile?:
          | T
          | {
              background?: T;
              experience?: T;
              languages?:
                | T
                | {
                    language?: T;
                    id?: T;
                  };
              specializations?:
                | T
                | {
                    specialization?: T;
                    id?: T;
                  };
            };
        guideRatings?:
          | T
          | {
              knowledgeScore?: T;
              engagementScore?: T;
              clarityScore?: T;
            };
      };
  seasonalConsiderations?:
    | T
    | {
        bestTime?: T;
        weatherImpact?: T;
        specialEvents?:
          | T
          | {
              event?: T;
              id?: T;
            };
        crowdingPatterns?: T;
      };
  reviewSnippets?:
    | T
    | {
        text?: T;
        source?: T;
        date?: T;
        rating?: T;
        visitorType?: T;
        id?: T;
      };
  location?:
    | T
    | {
        address?: T;
        neighborhood?: T;
        walkabilityScore?: T;
        parkingOptions?:
          | T
          | {
              type?: T;
              cost?: T;
              capacity?: T;
              walkTime?: T;
              name?: T;
              id?: T;
            };
        publicTransport?:
          | T
          | {
              nearestBusStop?: T;
              trainStation?: T;
              busRoutes?:
                | T
                | {
                    route?: T;
                    id?: T;
                  };
            };
        nearbyAttractions?:
          | T
          | {
              name?: T;
              walkTime?: T;
              type?: T;
              id?: T;
            };
      };
  businessInfo?:
    | T
    | {
        operator?: T;
        contact?:
          | T
          | {
              phone?: T;
              email?: T;
              website?: T;
              bookingPortal?: T;
            };
        operatedBy?: T;
        charitableStatus?: T;
      };
  reviews?:
    | T
    | {
        aggregate?:
          | T
          | {
              score?: T;
              count?: T;
              source?: T;
            };
        breakdown?:
          | T
          | {
              content?: T;
              guide?: T;
              value?: T;
              organization?: T;
              uniqueness?: T;
            };
      };
  relatedExperiences?:
    | T
    | {
        experienceId?: T;
        name?: T;
        relationship?: T;
        combinedBooking?: T;
        duration?: T;
        id?: T;
      };
  contextualInfo?:
    | T
    | {
        localContext?:
          | T
          | {
              culturalSignificance?: T;
              historicalImportance?: T;
              touristContext?: T;
            };
        bookingTips?:
          | T
          | {
              tip?: T;
              id?: T;
            };
        combinationSuggestions?:
          | T
          | {
              suggestion?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-pages_select".
 */
export interface WebPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
        schemaType?: T;
        keywords?: T;
        jsonLD?: T;
      };
  layout?:
    | T
    | {
        content?: T | ContentBlockSelect<T>;
        featureSection?: T | FeatureSectionSelect<T>;
        pricingCards?: T | PricingCardsBlockSelect<T>;
        featureComparisonTable?: T | FeatureComparisonTableBlockSelect<T>;
        brandLogos?: T | BrandLogosBlockSelect<T>;
        faqSection?: T | FaqSectionBlockSelect<T>;
        dashboardSection?: T | DashboardSectionBlockV2Select<T>;
        integrationsSection?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              titleImage?: T;
              logos?:
                | T
                | {
                    logoImage?: T;
                    altText?: T;
                    backgroundColorClass?: T;
                    id?: T;
                  };
              button?:
                | T
                | {
                    text?: T;
                    url?: T;
                    variant?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonialsSection?: T | TestimonialsSectionBlockSelect<T>;
        featuresWithIntroSection?: T | FeaturesWithIntroSectionBlockSelect<T>;
        heroSection02?: T | HeroSection02PayloadSelect<T>;
        WhyChooseUsSection?:
          | T
          | {
              eyebrowText?: T;
              eyebrowBackgroundColor?: T;
              title?: T;
              subTitle?: T;
              titleImage?: T;
              cards?:
                | T
                | {
                    icon?: T;
                    iconBackgroundColor?: T;
                    cardTitle?: T;
                    cardText?: T;
                    invertStyle?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        RecentArticles?: T | RecentArticlesBlockSelect<T>;
        ContactForm?: T | ContactFormBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureSection_select".
 */
export interface FeatureSectionSelect<T extends boolean = true> {
  sectionBackgroundColor?: T;
  contentBackgroundColor?: T;
  containerWidth?: T;
  superTitle?: T;
  title?: T;
  titleStyle?: T;
  description?: T;
  image?: T;
  button?:
    | T
    | {
        text?: T;
        url?: T;
        style?: T;
      };
  includeButton?: T;
  removeBottomPadding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingCardsBlock_select".
 */
export interface PricingCardsBlockSelect<T extends boolean = true> {
  eyebrowText?: T;
  title?: T;
  description?: T;
  headerImage?: T;
  enableBillingToggle?: T;
  sectionBackgroundColor?: T;
  removeTopPadding?: T;
  removeBottomPadding?: T;
  plans?:
    | T
    | {
        name?: T;
        description?: T;
        monthlyPrice?: T;
        annualPrice?: T;
        priceSuffix?: T;
        cardBackgroundColor?: T;
        ctaButtonLabel?: T;
        ctaButtonLink?: T;
        isMostPopular?: T;
        planSpecificFeatures?:
          | T
          | {
              featureText?: T;
              isIncluded?: T;
              tooltip?: T;
              id?: T;
            };
        id?: T;
      };
  sectionCtaText?: T;
  sectionCtaLink?: T;
  sectionCtaStyle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureComparisonTableBlock_select".
 */
export interface FeatureComparisonTableBlockSelect<T extends boolean = true> {
  eyebrowText?: T;
  title?: T;
  description?: T;
  headerImage?: T;
  sectionBackgroundColor?: T;
  removeTopPadding?: T;
  removeBottomPadding?: T;
  planHeaders?:
    | T
    | {
        name?: T;
        isMostPopular?: T;
        id?: T;
      };
  sharedFeatures?:
    | T
    | {
        featureName?: T;
        plan1Availability?: T;
        plan1CustomText?: T;
        plan2Availability?: T;
        plan2CustomText?: T;
        plan3Availability?: T;
        plan3CustomText?: T;
        tooltip?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandLogosBlock_select".
 */
export interface BrandLogosBlockSelect<T extends boolean = true> {
  title?: T;
  logos?:
    | T
    | {
        logoImage?: T;
        altText?: T;
        id?: T;
      };
  backgroundColor?: T;
  paddingTop?: T;
  paddingBottom?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqSectionBlock_select".
 */
export interface FaqSectionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  eyebrowBackgroundColor?: T;
  titleImage?: T;
  title?: T;
  description?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DashboardSectionBlockV2_select".
 */
export interface DashboardSectionBlockV2Select<T extends boolean = true> {
  eyebrowText?: T;
  eyebrowBackgroundColor?: T;
  title?: T;
  description?: T;
  primaryButton?:
    | T
    | {
        text?: T;
        url?: T;
      };
  image?: T;
  stats?:
    | T
    | {
        icon?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsSectionBlock_select".
 */
export interface TestimonialsSectionBlockSelect<T extends boolean = true> {
  eyebrowText?: T;
  titleImage?: T;
  title?: T;
  description?: T;
  caseStudies?:
    | T
    | {
        quoteTitle?: T;
        quote?: T;
        authorName?: T;
        authorImage?: T;
        authorRole?: T;
        companyLogo?: T;
        companyLogoBackgroundColor?: T;
        readMoreLink?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesWithIntroSectionBlock_select".
 */
export interface FeaturesWithIntroSectionBlockSelect<T extends boolean = true> {
  sectionBackgroundColor?: T;
  contentBackgroundColor?: T;
  removeTopPadding?: T;
  removeBottomPadding?: T;
  introContent?:
    | T
    | {
        superTitle?: T;
        eyebrowBackgroundColor?: T;
        title?: T;
        description?: T;
        titleImage?: T;
      };
  featureItems?:
    | T
    | {
        title?: T;
        titleStyle?: T;
        description?: T;
        image?: T;
        imagePosition?: T;
        imageBackgroundColor?: T;
        buttons?:
          | T
          | {
              text?: T;
              url?: T;
              style?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSection02Payload_select".
 */
export interface HeroSection02PayloadSelect<T extends boolean = true> {
  eyebrowText?: T;
  heading?: T;
  subheading?: T;
  buttons?:
    | T
    | {
        label?: T;
        variant?: T;
        type?: T;
        internalLink?: T;
        externalLink?: T;
        newTab?: T;
        id?: T;
      };
  heroImage?: T;
  arrowButtonText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RecentArticlesBlock_select".
 */
export interface RecentArticlesBlockSelect<T extends boolean = true> {
  eyebrowText?: T;
  eyebrowBackgroundColor?: T;
  title?: T;
  subTitle?: T;
  articles?:
    | T
    | {
        image?: T;
        eyebrowText?: T;
        articleEyebrowBackgroundColor?: T;
        articleTitle?: T;
        articleExcerpt?: T;
        buttonText?: T;
        link?:
          | T
          | {
              type?: T;
              label?: T;
              internalLink?: T;
              externalLink?: T;
              newTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock_select".
 */
export interface ContactFormBlockSelect<T extends boolean = true> {
  contentEyebrow?: T;
  contentTitle?: T;
  contentDescription?: T;
  contentImage?: T;
  contentImagePosition?: T;
  formTitle?: T;
  recipientEmail?: T;
  submitButtonText?: T;
  showNameField?: T;
  requireNameField?: T;
  showCompanyField?: T;
  requireCompanyField?: T;
  showSubjectField?: T;
  requireSubjectField?: T;
  showMessageField?: T;
  requireMessageField?: T;
  messageFieldLabel?: T;
  privacyPolicyText?: T;
  link?:
    | T
    | {
        type?: T;
        label?: T;
        internalLink?: T;
        externalLink?: T;
        newTab?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wiki-pages_select".
 */
export interface WikiPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  pageBuilder?:
    | T
    | {
        content?: T | ContentBlockSelect<T>;
      };
  status?: T;
  sort?: T;
  isSectionHomepage?: T;
  parent?: T;
  icon?: T;
  iconBackgroundColor?: T;
  backgroundSettings?:
    | T
    | {
        backgroundImage?: T;
        backgroundOverlay?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
        schemaType?: T;
        keywords?: T;
        jsonLD?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registry-pages_select".
 */
export interface RegistryPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  template?: T;
  pageBuilder?:
    | T
    | {
        content?: T | ContentBlockSelect<T>;
        regRichText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        regCallout?:
          | T
          | {
              content?: T;
              backgroundColor?: T;
              icon?: T;
              id?: T;
              blockName?: T;
            };
        regImageCarousel?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              visibleThumbnails?: T;
              id?: T;
              blockName?: T;
            };
        regColumns?:
          | T
          | {
              columns?:
                | T
                | {
                    blocks?:
                      | T
                      | {
                          regRichText?:
                            | T
                            | {
                                content?: T;
                                id?: T;
                                blockName?: T;
                              };
                          regCallout?:
                            | T
                            | {
                                content?: T;
                                backgroundColor?: T;
                                icon?: T;
                                id?: T;
                                blockName?: T;
                              };
                          regCode?:
                            | T
                            | {
                                title?: T;
                                code?: T;
                                showBorder?: T;
                                id?: T;
                                blockName?: T;
                              };
                          regImageCarousel?:
                            | T
                            | {
                                images?:
                                  | T
                                  | {
                                      image?: T;
                                      id?: T;
                                    };
                                visibleThumbnails?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        regAccordion?:
          | T
          | {
              items?:
                | T
                | {
                    title?: T;
                    content?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        regTable?:
          | T
          | {
              rows?:
                | T
                | {
                    cells?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        regCode?:
          | T
          | {
              title?: T;
              code?: T;
              showBorder?: T;
              id?: T;
              blockName?: T;
            };
      };
  status?: T;
  sort?: T;
  isSectionHomepage?: T;
  parent?: T;
  icon?: T;
  iconBackgroundColor?: T;
  backgroundSettings?:
    | T
    | {
        backgroundImage?: T;
        backgroundOverlay?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
        schemaType?: T;
        keywords?: T;
        jsonLD?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-cache_select".
 */
export interface NavigationCacheSelect<T extends boolean = true> {
  section?: T;
  navigationData?: T;
  lastGenerated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-templates_select".
 */
export interface PageTemplatesSelect<T extends boolean = true> {
  name?: T;
  blocks?:
    | T
    | {
        regRichText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        regCallout?:
          | T
          | {
              content?: T;
              backgroundColor?: T;
              icon?: T;
              id?: T;
              blockName?: T;
            };
        regImageCarousel?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              visibleThumbnails?: T;
              id?: T;
              blockName?: T;
            };
        regColumns?:
          | T
          | {
              columns?:
                | T
                | {
                    blocks?:
                      | T
                      | {
                          regRichText?:
                            | T
                            | {
                                content?: T;
                                id?: T;
                                blockName?: T;
                              };
                          regCallout?:
                            | T
                            | {
                                content?: T;
                                backgroundColor?: T;
                                icon?: T;
                                id?: T;
                                blockName?: T;
                              };
                          regCode?:
                            | T
                            | {
                                title?: T;
                                code?: T;
                                showBorder?: T;
                                id?: T;
                                blockName?: T;
                              };
                          regImageCarousel?:
                            | T
                            | {
                                images?:
                                  | T
                                  | {
                                      image?: T;
                                      id?: T;
                                    };
                                visibleThumbnails?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        regAccordion?:
          | T
          | {
              items?:
                | T
                | {
                    title?: T;
                    content?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        regTable?:
          | T
          | {
              rows?:
                | T
                | {
                    cells?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        regCode?:
          | T
          | {
              title?: T;
              code?: T;
              showBorder?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  ctaEnable?: boolean | null;
  ctaPreTitle?: string | null;
  ctaEyebrowBackgroundColor?:
    | (
        | 'theme-color-01'
        | 'theme-color-02'
        | 'theme-color-03'
        | 'theme-color-04'
        | 'purple'
        | 'green'
        | 'yellow'
        | 'purple-light'
        | 'default'
      )
    | null;
  ctaTitle?: string | null;
  ctaDescription?: string | null;
  ctaButtonText?: string | null;
  ctaButtonLink?: string | null;
  /**
   * Optional: Image displayed in the CTA section, typically on the right.
   */
  ctaImage?: (string | null) | Media;
  logo?: (string | null) | Media;
  tagline?: string | null;
  linkColumns?:
    | {
        title: string;
        links?:
          | {
              text: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  subscribePlaceholder?: string | null;
  newsletterTitle?: string | null;
  socialLinks?:
    | {
        /**
         * Enter the Phosphor Icon name (e.g., TwitterLogo, LinkedinLogo). Do not include "Ph".
         */
        iconName: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  copyright: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  ctaEnable?: T;
  ctaPreTitle?: T;
  ctaEyebrowBackgroundColor?: T;
  ctaTitle?: T;
  ctaDescription?: T;
  ctaButtonText?: T;
  ctaButtonLink?: T;
  ctaImage?: T;
  logo?: T;
  tagline?: T;
  linkColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              text?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  subscribePlaceholder?: T;
  newsletterTitle?: T;
  socialLinks?:
    | T
    | {
        iconName?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}